### ISSUE TITLE
Bad broadway component type

### ISSUE THREAD

**Issue by r4sheed** [Open-GTO/zvehcomp#2]
Hey!

I've noticed broadway has bad front and rear bumper types.
For example:

> 1174 Front Bumper
> 1176 Rear Bumper

has CARMODTYPE_FRONT_BUMPER component type.

and 

> 1175 Slamin Front Bumper
> 1177 Slamin Rear Bumper

has with CARMODTYPE_REAR_BUMPER type.

**Comment by 0x416c69** [comment]
What the heck are you talking about

**Comment by r4sheed** [comment]
> 
> 
> What the heck are you talking about

1176 (Rear Bumper) has CARMODTYPE_FRONT_BUMPER and  1175 (Slamin Front Bumper) has CARMODTYPE_REAR_BUMPER  type. What is difficult to understand? The component id's are commuted.
